version: '3.9'

services:
  mongo:
    hostname: mongo
    image: mongo:8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: datasets
    volumes:
      - mongo_data:/data/db
      - ./datasets:/var/opt/mongo/datasets
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mongo_data:
